//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPhoneStoreApplication
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class AdminLogin
    {
        [DisplayName("Admin ID")]
        public string AdminID { get; set; }

        [DisplayName("Admin Password")]
        public string AdminPassword { get; set; }
    }
}
