//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartPhoneStoreApplication
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Order
    {
        [DisplayName("Order ID")]
        public int OrderID { get; set; }

        [DisplayName("Customer ID")]
        public Nullable<int> CustomerID { get; set; }

        [DisplayName("Product ID")]
        public Nullable<int> ProductID { get; set; }

        [DisplayName("Quantity")]
        public Nullable<int> Quantity { get; set; }

        [DisplayName("Order Status")]
        public string OrderStatus { get; set; }

        [DisplayName("Ordered Date")]
        public Nullable<System.DateTime> OrderedDate { get; set; }

        [DisplayName("Expected Date")]
        public Nullable<System.DateTime> ExpectedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
